[package]
name = "thisdefmterror-macros"
version = "0.1.0"
edition = "2024"

[features]
defmt = []

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
regex = "1.11"
proc-macro2 = "1.0"