[package]
name = "thisdefmterror"
version = "0.1.0"
edition = "2024"

[features]
default = ["defmt"]
defmt = ["dep:defmt", "thisdefmterror-macros/defmt"]

[dependencies]
defmt = { workspace = true, optional = true }
thisdefmterror-macros = {path = "../thisdefmterror-macros"}